from yacs.config import CfgNode as CN


_C = CN()

_C.ANNOTATE = CN()
_C.ANNOTATE.TRIALS = []
_C.ANNOTATE.FRAME_IDS = [0, 0, 0]
_C.ANNOTATE.MAX_DIST_TO_MESH = 0.1

_C.CALIBRATION = CN()
_C.CALIBRATION.TRIALS = []
_C.CALIBRATION._X = 0.
_C.CALIBRATION._Y = 0.
_C.CALIBRATION._Z = 0.
_C.CALIBRATION.GROUND = 0.
_C.CALIBRATION.VOXEL_SPACE = 0.01
_C.CALIBRATION.NB_POINTS = 100
_C.CALIBRATION.RADIUS = 0.1

_C.VISUALIZE  = CN()
_C.VISUALIZE.TRIAL = ''
_C.VISUALIZE.FRAME_IDS = [0, 0, 0]


def get_cfg_defaults():
    return _C.clone()
